name: Send GraphQL Mutation

on: [push]  # Trigger the workflow on push events

jobs:
  send-mutation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE

    - name: Send GraphQL Mutation
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the built-in GITHUB_TOKEN
      run: |
        GRAPHQL_QUERY=$(cat <<EOF
        mutation {
          updateProjectV2(input: {
            title: "test"
            projectId: "PVT_kwDOBjcuK84AYDky"
          }) {
            clientMutationId
          }
        }
        EOF
        )

        curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" -H "Content-Type: application/json" --data "{ \"query\": \"$GRAPHQL_QUERY\" }" https://api.github.com/graphql
